name: Verify Unity License

on:
  workflow_dispatch: {}

jobs:

  verifyUnityLicense:
  
    name: Verify Unity License
    
    runs-on: ubuntu-latest
    
    steps:
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
        
      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      
      # Verify our Unity License is OK.
      - name: Activate Unity
        uses: game-ci/unity-activate@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        
      # Return our license to free up a license usage spot.
      - name: Unity - Return License
        uses: game-ci/unity-return-license@v2.0.0
        
